# Use Python 3.12.7 as the base, the same as our conda environment
FROM python:3.12.7-slim

# Install system dependencies required for torchaudio
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Set up working directory
WORKDIR /app

# Copy files to the container
COPY asr/asr_api.py /app/
COPY ../requirements.txt /app/

# Install dependencies
RUN pip install -r requirements.txt

# Expose the port the app runs on
EXPOSE 8001

# Command to run the application
CMD ["python", "asr_api.py"]